on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y gcc
    - run: mkdir -p bin
    - run: gcc -Wall -std=c99 -o bin/main subset_iterator.c
    - run: echo "Build successful"
